version: "3.9"
services:
  nodejs:
    container_name: nodejs-container
    image: nnnnisidle/note-taking-app:1.0.1
    restart: always
    ports: 
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb-container
    image: mongo
    restart: always
    ports: 
      - "27017:27017"
